FROM ubuntu:20.04

WORKDIR /home/user

RUN apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get install -y \
        cmake \
        curl \
        git \
        vim \
        libpoppler-cpp-dev \
        libtesseract-dev \
        pkg-config \
        poppler-utils \
        python3-pip \
        python3.9 \
        python3.9-dev \
        python3.9-distutils \
        wget && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade streamlit
RUN pip install streamlit-authenticator
RUN pip install streamlit-extras

EXPOSE 8501

COPY ./ /home/user/frontend

COPY ./.streamlit/secrets.toml /home/user/.streamlit/secrets.toml