FROM ubuntu:20.04

WORKDIR /home/user

RUN apt-get update && apt-get install -y software-properties-common && \
    apt-get install -y \
        curl \
        git \
        vim \
        python3.9 \
        python3.9-dev \
        python3.9-distutils \
        python3-pip \
        wget && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade streamlit
RUN pip install streamlit-authenticator
RUN pip install bs4

EXPOSE 8501

COPY ./ /home/user/frontend

COPY ./.streamlit/secrets.toml /home/user/.streamlit/secrets.toml