version: "3"
services:
  scratchpad-api:
    build:
      context: scratchpad
      dockerfile: DOCKERFILE-CPU
    image: "scratchpad-docker-cpu:0.1"
    # in recent docker-compose version you can enable GPU resources. Make sure to fulfill the prerequisites listed here: https://docs.docker.com/compose/gpu-support/
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch
      - cluster.name=docker-cluster
      - TOKENIZERS_PARALLELISM=false
    depends_on:
      - elasticsearch
    command: "/bin/bash -c 'sleep 10 && gunicorn scratchpad.app.main:app -b 0.0.0.0 -k uvicorn.workers.UvicornWorker --workers 1 --timeout 180'"

  elasticsearch:
    # This will start an empty elasticsearch instance (so you have to add your documents yourself)
    image: "elasticsearch:7.9.2"
    container_name: elasticsearch
    ports:
      - 9200:9200
    restart: on-failure
    environment:
      - discovery.type=single-node
    volumes:
      - ./esdata:/var/lib/elasticsearch/data:rw

  ui:
    build:
      context: frontend
      dockerfile: DOCKERFILE-FRONTEND
    image: scratchpad-docker:frontend_0.2
    ports:
      - 8501:8501
    restart: on-failure
    environment:
      - API_ENDPOINT=http://scratchpad-api:8000
    command: "/bin/bash -c 'streamlit run frontend/landing_page.py'"
